server:
  port: 8080

spring:
  velocity:
    charset: UTF-8
    properties:
      input.encoding: UTF-8
      output.encoding: UTF-8
      velocimacro.library: macros.vm
      velocimacro.library.autoreload: true
    cache: false
    toolbox-config-location: toolbox.xml
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
    username: ongo360
    password: ongo360
    virtual-host: ongo360_vhost

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

default:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true // All operations should be idempotent

logging:
  path: /var/log
  level:
    root: WARN
    com:
      ongo360:
        demo: DEBUG

configTestValue: 'Hello 云梯 改一下+2'
